package mx.itesm.rmroman.proyectobasegpo01;
/**
 * Define los tipos de escena del juego (Pantallas)
 *
 * @author Roberto Martínez Román
 */
public enum TipoEscena {
    ESCENA_SPLASH,
    ESCENA_MENU,
    ESCENA_ACERCA_DE,
    ESCENA_HISTORIA_INTRO,
    ESCENA_SPLASH_HUNTING_COWS,
    ESCENA_CAZA_JURASICA,
    ESCENA_COMIC,
    ESCENA_CARGANDO,
    ESCENA_AJUSTES,
    ESCENA_INTRO_CAZA_JURASICA,
    ESCENA_CAZA_JURASICA_NIVEL_2,
    ESCENA_HISTORIA_CAZA_JURASICA,
    ESCENA_PERDISTE,
    ESCENA_GANASTE,
    ESCENA_ESCENA_PELEA_BOSS_CAZA_JURASICA,
    ESCENA_ARCADE,
    ESCENA_ALEATORIEDAD,
    ESCENA_LABERINTO_UNO
}
